name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_DEFAULT_REGION: us-west-2
  AWS_REGION: us-west-2
  GITHUB_ACTIONS: true
  AWS_ACCESS_KEY_ID: ${{ secrets.DEVOPS_STAGING_AWS_ACCESS_KEY_ID }}
  AWS_SECCRET_ACCESS_KEY: ${{ secrets.DEVOPS_STAGING_AWS_SECRET_ACCESS_KEY }}
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_ICON: https://github.githubassets.com/images/modules/site/features/actions-icon-actions.svg
  SLACK_CHANNEL: academic-pillar-qe

jobs:
  notify-slack-on-start:
    runs-on: ubuntu-latest
    steps:
      - uses: rtCamp/action-slack-notify@v2.0.2
        name: notify slack on run start
        env:
          SLACK_TITLE: Academic E2E Regression
          SLACK_COLOR: good
          SLACK_MESSAGE: 'GUI Automation has started :white_check_mark:'

  test:
    needs: [notify-slack-on-start]
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECCRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Install dependencies
      run: yarn install

    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps

    - name: Run Playwright tests
      run: yarn test
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 20

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: allure-results
        path: allure-results
        retention-days: 20
        
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    
    - name: Test marketplace action
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history

    - uses: rtCamp/action-slack-notify@v2.0.2
      name: notify slack on failure
      if: failure()
      env:
          SLACK_TITLE: Test(s) failed while running in Staging
          SLACK_COLOR: danger
          SLACK_MESSAGE: ':failed: :computer-rage: Automation Failure on Staging! <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>'
             
  notify-slack-on-completion:
       needs: test
       runs-on: ubuntu-latest
       steps:
         - uses: rtCamp/action-slack-notify@v2.0.2
           name: notify slack on run completion
           env:
            SLACK_TITLE: Academic E2E Regression
            SLACK_COLOR: good
            SLACK_MESSAGE: ':pass: :white_check_mark: Automation Successful on Staging! <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>'
  
  
  


